import './globals.css'
import { Inter } from 'next/font/google'
import Header from '@/components/layout/Header'
import Wraper from '@/components/layout/wraper'
import Footer from '@/components/layout/footer'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className="{inter.className} px-8 pt-4" >
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  )
}
